require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe KIndactivitiesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # KIndactivity. As you add validations to KIndactivity, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # KIndactivitiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all k_indactivities as @k_indactivities" do
      k_indactivity = KIndactivity.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:k_indactivities)).to eq([k_indactivity])
    end
  end

  describe "GET show" do
    it "assigns the requested k_indactivity as @k_indactivity" do
      k_indactivity = KIndactivity.create! valid_attributes
      get :show, {:id => k_indactivity.to_param}, valid_session
      expect(assigns(:k_indactivity)).to eq(k_indactivity)
    end
  end

  describe "GET new" do
    it "assigns a new k_indactivity as @k_indactivity" do
      get :new, {}, valid_session
      expect(assigns(:k_indactivity)).to be_a_new(KIndactivity)
    end
  end

  describe "GET edit" do
    it "assigns the requested k_indactivity as @k_indactivity" do
      k_indactivity = KIndactivity.create! valid_attributes
      get :edit, {:id => k_indactivity.to_param}, valid_session
      expect(assigns(:k_indactivity)).to eq(k_indactivity)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new KIndactivity" do
        expect {
          post :create, {:k_indactivity => valid_attributes}, valid_session
        }.to change(KIndactivity, :count).by(1)
      end

      it "assigns a newly created k_indactivity as @k_indactivity" do
        post :create, {:k_indactivity => valid_attributes}, valid_session
        expect(assigns(:k_indactivity)).to be_a(KIndactivity)
        expect(assigns(:k_indactivity)).to be_persisted
      end

      it "redirects to the created k_indactivity" do
        post :create, {:k_indactivity => valid_attributes}, valid_session
        expect(response).to redirect_to(KIndactivity.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved k_indactivity as @k_indactivity" do
        post :create, {:k_indactivity => invalid_attributes}, valid_session
        expect(assigns(:k_indactivity)).to be_a_new(KIndactivity)
      end

      it "re-renders the 'new' template" do
        post :create, {:k_indactivity => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested k_indactivity" do
        k_indactivity = KIndactivity.create! valid_attributes
        put :update, {:id => k_indactivity.to_param, :k_indactivity => new_attributes}, valid_session
        k_indactivity.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested k_indactivity as @k_indactivity" do
        k_indactivity = KIndactivity.create! valid_attributes
        put :update, {:id => k_indactivity.to_param, :k_indactivity => valid_attributes}, valid_session
        expect(assigns(:k_indactivity)).to eq(k_indactivity)
      end

      it "redirects to the k_indactivity" do
        k_indactivity = KIndactivity.create! valid_attributes
        put :update, {:id => k_indactivity.to_param, :k_indactivity => valid_attributes}, valid_session
        expect(response).to redirect_to(k_indactivity)
      end
    end

    describe "with invalid params" do
      it "assigns the k_indactivity as @k_indactivity" do
        k_indactivity = KIndactivity.create! valid_attributes
        put :update, {:id => k_indactivity.to_param, :k_indactivity => invalid_attributes}, valid_session
        expect(assigns(:k_indactivity)).to eq(k_indactivity)
      end

      it "re-renders the 'edit' template" do
        k_indactivity = KIndactivity.create! valid_attributes
        put :update, {:id => k_indactivity.to_param, :k_indactivity => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested k_indactivity" do
      k_indactivity = KIndactivity.create! valid_attributes
      expect {
        delete :destroy, {:id => k_indactivity.to_param}, valid_session
      }.to change(KIndactivity, :count).by(-1)
    end

    it "redirects to the k_indactivities list" do
      k_indactivity = KIndactivity.create! valid_attributes
      delete :destroy, {:id => k_indactivity.to_param}, valid_session
      expect(response).to redirect_to(k_indactivities_url)
    end
  end

end
