require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TableServiceOrdersController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # TableServiceOrder. As you add validations to TableServiceOrder, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TableServiceOrdersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all table_service_orders as @table_service_orders" do
      table_service_order = TableServiceOrder.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:table_service_orders)).to eq([table_service_order])
    end
  end

  describe "GET show" do
    it "assigns the requested table_service_order as @table_service_order" do
      table_service_order = TableServiceOrder.create! valid_attributes
      get :show, {:id => table_service_order.to_param}, valid_session
      expect(assigns(:table_service_order)).to eq(table_service_order)
    end
  end

  describe "GET new" do
    it "assigns a new table_service_order as @table_service_order" do
      get :new, {}, valid_session
      expect(assigns(:table_service_order)).to be_a_new(TableServiceOrder)
    end
  end

  describe "GET edit" do
    it "assigns the requested table_service_order as @table_service_order" do
      table_service_order = TableServiceOrder.create! valid_attributes
      get :edit, {:id => table_service_order.to_param}, valid_session
      expect(assigns(:table_service_order)).to eq(table_service_order)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TableServiceOrder" do
        expect {
          post :create, {:table_service_order => valid_attributes}, valid_session
        }.to change(TableServiceOrder, :count).by(1)
      end

      it "assigns a newly created table_service_order as @table_service_order" do
        post :create, {:table_service_order => valid_attributes}, valid_session
        expect(assigns(:table_service_order)).to be_a(TableServiceOrder)
        expect(assigns(:table_service_order)).to be_persisted
      end

      it "redirects to the created table_service_order" do
        post :create, {:table_service_order => valid_attributes}, valid_session
        expect(response).to redirect_to(TableServiceOrder.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved table_service_order as @table_service_order" do
        post :create, {:table_service_order => invalid_attributes}, valid_session
        expect(assigns(:table_service_order)).to be_a_new(TableServiceOrder)
      end

      it "re-renders the 'new' template" do
        post :create, {:table_service_order => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested table_service_order" do
        table_service_order = TableServiceOrder.create! valid_attributes
        put :update, {:id => table_service_order.to_param, :table_service_order => new_attributes}, valid_session
        table_service_order.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested table_service_order as @table_service_order" do
        table_service_order = TableServiceOrder.create! valid_attributes
        put :update, {:id => table_service_order.to_param, :table_service_order => valid_attributes}, valid_session
        expect(assigns(:table_service_order)).to eq(table_service_order)
      end

      it "redirects to the table_service_order" do
        table_service_order = TableServiceOrder.create! valid_attributes
        put :update, {:id => table_service_order.to_param, :table_service_order => valid_attributes}, valid_session
        expect(response).to redirect_to(table_service_order)
      end
    end

    describe "with invalid params" do
      it "assigns the table_service_order as @table_service_order" do
        table_service_order = TableServiceOrder.create! valid_attributes
        put :update, {:id => table_service_order.to_param, :table_service_order => invalid_attributes}, valid_session
        expect(assigns(:table_service_order)).to eq(table_service_order)
      end

      it "re-renders the 'edit' template" do
        table_service_order = TableServiceOrder.create! valid_attributes
        put :update, {:id => table_service_order.to_param, :table_service_order => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested table_service_order" do
      table_service_order = TableServiceOrder.create! valid_attributes
      expect {
        delete :destroy, {:id => table_service_order.to_param}, valid_session
      }.to change(TableServiceOrder, :count).by(-1)
    end

    it "redirects to the table_service_orders list" do
      table_service_order = TableServiceOrder.create! valid_attributes
      delete :destroy, {:id => table_service_order.to_param}, valid_session
      expect(response).to redirect_to(table_service_orders_url)
    end
  end

end
